### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Evoluange** [kemaloksuz/RankSortLoss-Solov2#1]
Hi,
thanks for sharing the code!

when I run " python tools/train.py configs/ranksort_loss/ranksort_solov2_light_448_r34_fpn_3x.py", but error occur  in mmdet/models/anchor_heads/rank_based_solov2_head.py
" 
flat_labels[flat_labels==1.] = 1-loss_instances.detach()
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Float for the source.
"
I found that flat_labels type is torch.int64 ,and loss_instances type is torch.float32, 
 
it may be have some problems in the code.

**Comment by kemaloksuz** [comment]
Many thanks. This error is fixed now.
